package net.rsprot.protocol.common.js5.outgoing.prot

import net.rsprot.protocol.Prot
import net.rsprot.protocol.ServerProt

public enum class Js5ServerProt(
    override val opcode: Int,
    override val size: Int,
) : ServerProt {
    // Interface related packets
    IF_INITIALSTATE(Js5ServerProtId.IF_INITIALSTATE, Prot.VAR_SHORT),
    IF_OPENTOP(Js5ServerProtId.IF_OPENTOP, 2),
    IF_OPENSUB(Js5ServerProtId.IF_OPENSUB, 7),
    IF_CLOSESUB(Js5ServerProtId.IF_CLOSESUB, 4),
    IF_MOVESUB(Js5ServerProtId.IF_MOVESUB, 8),
    IF_CLEARINV(Js5ServerProtId.IF_CLEARINV, 4),
    IF_SETEVENTS(Js5ServerProtId.IF_SETEVENTS, 12),
    IF_SETPOSITION(Js5ServerProtId.IF_SETPOSITION, 8),
    IF_SETSCROLLPOS(Js5ServerProtId.IF_SETSCROLLPOS, 6),
    IF_SETROTATESPEED(Js5ServerProtId.IF_SETROTATESPEED, 8),
    IF_SETTEXT(Js5ServerProtId.IF_SETTEXT, Prot.VAR_SHORT),
    IF_SETHIDE(Js5ServerProtId.IF_SETHIDE, 5),
    IF_SETANGLE(Js5ServerProtId.IF_SETANGLE, 10),
    IF_SETOBJECT(Js5ServerProtId.IF_SETOBJECT, 10),
    IF_SETCOLOUR(Js5ServerProtId.IF_SETCOLOUR, 6),
    IF_SETANIM(Js5ServerProtId.IF_SETANIM, 6),
    IF_SETNPCHEAD(Js5ServerProtId.IF_SETNPCHEAD, 6),
    IF_SETNPCHEAD_ACTIVE(Js5ServerProtId.IF_SETNPCHEAD_ACTIVE, 6),
    IF_SETPLAYERHEAD(Js5ServerProtId.IF_SETPLAYERHEAD, 4),
    IF_SETMODEL(Js5ServerProtId.IF_SETMODEL, 6),
    IF_SETPLAYERMODEL_BASECOLOUR(Js5ServerProtId.IF_SETPLAYERMODEL_BASECOLOUR, 6),
    IF_SETPLAYERMODEL_BODYTYPE(Js5ServerProtId.IF_SETPLAYERMODEL_BODYTYPE, 5),
    IF_SETPLAYERMODEL_OBJ(Js5ServerProtId.IF_SETPLAYERMODEL_OBJ, 8),
    IF_SETPLAYERMODEL_SELF(Js5ServerProtId.IF_SETPLAYERMODEL_SELF, 5),

    // Music-system related packets (excl. zone ones)
    MIDI_SONG(Js5ServerProtId.MIDI_SONG, 10),
    MIDI_SONG_WITHSECONDARY(Js5ServerProtId.MIDI_SONG_WITHSECONDARY, 12),
    MIDI_SWAP(Js5ServerProtId.MIDI_SWAP, 8),
    MIDI_SONG_STOP(Js5ServerProtId.MIDI_SONG_STOP, 4),
    MIDI_SONG_OLD(Js5ServerProtId.MIDI_SONG_OLD, 2),
    MIDI_JINGLE(Js5ServerProtId.MIDI_JINGLE, 5),
    SYNTH_SOUND(Js5ServerProtId.SYNTH_SOUND, 5),

    // Zone header packets
    UPDATE_ZONE_FULL_FOLLOWS(Js5ServerProtId.UPDATE_ZONE_FULL_FOLLOWS, 3),
    UPDATE_ZONE_PARTIAL_FOLLOWS(Js5ServerProtId.UPDATE_ZONE_PARTIAL_FOLLOWS, 3),
    UPDATE_ZONE_PARTIAL_ENCLOSED(Js5ServerProtId.UPDATE_ZONE_PARTIAL_ENCLOSED, Prot.VAR_SHORT),

    // Zone payload packets
    LOC_ADD_CHANGE(Js5ServerProtId.LOC_ADD_CHANGE, 5),
    LOC_DEL(Js5ServerProtId.LOC_DEL, 2),
    LOC_ANIM(Js5ServerProtId.LOC_ANIM, 4),
    LOC_MERGE(Js5ServerProtId.LOC_MERGE, 14),
    OBJ_ADD(Js5ServerProtId.OBJ_ADD, 14),
    OBJ_DEL(Js5ServerProtId.OBJ_DEL, 7),
    OBJ_COUNT(Js5ServerProtId.OBJ_COUNT, 11),
    OBJ_OPFILTER(Js5ServerProtId.OBJ_OPFILTER, 4),
    MAP_ANIM(Js5ServerProtId.MAP_ANIM, 6),
    MAP_PROJANIM(Js5ServerProtId.MAP_PROJANIM, 20),
    SOUND_AREA(Js5ServerProtId.SOUND_AREA, 7),

    // Specific packets
    PROJANIM_SPECIFIC(Js5ServerProtId.PROJANIM_SPECIFIC, 19),

    @Deprecated(
        "Deprecated as it is bugged(size: 17; payload: 18) and " +
            "a newer variant with greater property ranges is introduced",
        replaceWith = ReplaceWith("PROJANIM_SPECIFIC"),
    )
    PROJANIM_SPECIFIC_OLD(Js5ServerProtId.PROJANIM_SPECIFIC_OLD, 17),
    MAP_ANIM_SPECIFIC(Js5ServerProtId.MAP_ANIM_SPECIFIC, 8),
    LOC_ANIM_SPECIFIC(Js5ServerProtId.LOC_ANIM_SPECIFIC, 6),
    NPC_HEADICON_SPECIFIC(Js5ServerProtId.NPC_HEADICON_SPECIFIC, 9),
    NPC_SPOTANIM_SPECIFIC(Js5ServerProtId.NPC_SPOTANIM_SPECIFIC, 9),
    NPC_ANIM_SPECIFIC(Js5ServerProtId.NPC_ANIM_SPECIFIC, 5),
    PLAYER_ANIM_SPECIFIC(Js5ServerProtId.PLAYER_ANIM_SPECIFIC, 3),
    PLAYER_SPOTANIM_SPECIFIC(Js5ServerProtId.PLAYER_SPOTANIM_SPECIFIC, 9),

    // Info packets
    PLAYER_INFO(Js5ServerProtId.PLAYER_INFO, Prot.VAR_SHORT),
    NPC_INFO_SMALL(Js5ServerProtId.NPC_INFO_SMALL, Prot.VAR_SHORT),
    NPC_INFO_LARGE(Js5ServerProtId.NPC_INFO_LARGE, Prot.VAR_SHORT),

    // Map packets
    REBUILD_NORMAL(Js5ServerProtId.REBUILD_NORMAL, Prot.VAR_SHORT),
    REBUILD_REGION(Js5ServerProtId.REBUILD_REGION, Prot.VAR_SHORT),

    // Varp packets
    VARP_SMALL(Js5ServerProtId.VARP_SMALL, 3),
    VARP_LARGE(Js5ServerProtId.VARP_LARGE, 6),
    VARP_RESET(Js5ServerProtId.VARP_RESET, 0),
    VARP_SYNC(Js5ServerProtId.VARP_SYNC, 0),

    // Camera packets
    CAM_SHAKE(Js5ServerProtId.CAM_SHAKE, 4),
    CAM_RESET(Js5ServerProtId.CAM_RESET, 0),
    CAM_SMOOTHRESET(Js5ServerProtId.CAM_SMOOTH_RESET, 4),
    CAM_MOVETO(Js5ServerProtId.CAM_MOVETO, 6),
    CAM_MOVETO_EASED(Js5ServerProtId.CAM_MOVETO_EASED, 8),
    CAM_MOVETO_EASED_CIRCULAR(Js5ServerProtId.CAM_MOVETO_EASED_CIRCULAR, 10),
    CAM_LOOKAT(Js5ServerProtId.CAM_LOOKAT, 6),
    CAM_LOOKAT_EASED_COORD(Js5ServerProtId.CAM_LOOKAT_EASED_COORD, 7),
    CAM_LOOKAT_EASED_ANGLE_RELATIVE(Js5ServerProtId.CAM_LOOKAT_EASED_ANGLE_RELATIVE, 7),
    CAM_LOOKAT_EASED_ANGLE_ABSOLUTE(Js5ServerProtId.CAM_LOOKAT_EASED_ANGLE_ABSOLUTE, 7),
    CAM_MODE(Js5ServerProtId.CAM_MODE, 1),
    OCULUS_SYNC(Js5ServerProtId.OCULUS_SYNC, 4),

    // Inventory packets
    UPDATE_INV_FULL(Js5ServerProtId.UPDATE_INV_FULL, Prot.VAR_SHORT),
    UPDATE_INV_PARTIAL(Js5ServerProtId.UPDATE_INV_PARTIAL, Prot.VAR_SHORT),
    UPDATE_INV_STOPTRANSMIT(Js5ServerProtId.UPDATE_INV_STOPTRANSMIT, 2),

    // Social packets
    MESSAGE_PRIVATE(Js5ServerProtId.MESSAGE_PRIVATE, Prot.VAR_SHORT),
    MESSAGE_PRIVATE_ECHO(Js5ServerProtId.MESSAGE_PRIVATE_ECHO, Prot.VAR_SHORT),
    FRIENDLIST_LOADED(Js5ServerProtId.FRIENDLIST_LOADED, 0),
    UPDATE_FRIENDLIST(Js5ServerProtId.UPDATE_FRIENDLIST, Prot.VAR_SHORT),
    UPDATE_IGNORELIST(Js5ServerProtId.UPDATE_IGNORELIST, Prot.VAR_SHORT),

    // Friend chat (old "clans") packets
    UPDATE_FRIENDCHAT_CHANNEL_FULL_V1(Js5ServerProtId.UPDATE_FRIENDCHAT_CHANNEL_FULL_V1, Prot.VAR_SHORT),
    UPDATE_FRIENDCHAT_CHANNEL_FULL_V2(Js5ServerProtId.UPDATE_FRIENDCHAT_CHANNEL_FULL_V2, Prot.VAR_SHORT),
    UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER(Js5ServerProtId.UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER, Prot.VAR_BYTE),
    MESSAGE_FRIENDCHANNEL(Js5ServerProtId.MESSAGE_FRIENDCHANNEL, Prot.VAR_BYTE),

    // Clan chat packets
    VARCLAN(Js5ServerProtId.VARCLAN, Prot.VAR_BYTE),
    VARCLAN_ENABLE(Js5ServerProtId.VARCLAN_ENABLE, 0),
    VARCLAN_DISABLE(Js5ServerProtId.VARCLAN_DISABLE, 0),
    CLANCHANNEL_FULL(Js5ServerProtId.CLANCHANNEL_FULL, Prot.VAR_SHORT),
    CLANCHANNEL_DELTA(Js5ServerProtId.CLANCHANNEL_DELTA, Prot.VAR_SHORT),
    CLANSETTINGS_FULL(Js5ServerProtId.CLANSETTINGS_FULL, Prot.VAR_SHORT),
    CLANSETTINGS_DELTA(Js5ServerProtId.CLANSETTINGS_DELTA, Prot.VAR_SHORT),
    MESSAGE_CLANCHANNEL(Js5ServerProtId.MESSAGE_CLANCHANNEL, Prot.VAR_BYTE),
    MESSAGE_CLANCHANNEL_SYSTEM(Js5ServerProtId.MESSAGE_CLANCHANNEL_SYSTEM, Prot.VAR_BYTE),

    // Log out packets
    LOGOUT(Js5ServerProtId.LOGOUT, 0),
    LOGOUT_WITHREASON(Js5ServerProtId.LOGOUT_WITHREASON, 1),
    LOGOUT_TRANSFER(Js5ServerProtId.LOGOUT_TRANSFER, Prot.VAR_BYTE),

    // Misc. player state packets
    UPDATE_RUNWEIGHT(Js5ServerProtId.UPDATE_RUNWEIGHT, 2),
    UPDATE_RUNENERGY(Js5ServerProtId.UPDATE_RUNENERGY, 2),
    SET_MAP_FLAG(Js5ServerProtId.SET_MAP_FLAG, 2),
    SET_PLAYER_OP(Js5ServerProtId.SET_PLAYER_OP, Prot.VAR_BYTE),
    UPDATE_STAT(Js5ServerProtId.UPDATE_STAT, 7),
    UPDATE_STAT_OLD(Js5ServerProtId.UPDATE_STAT_OLD, 6),

    // Misc. player packets
    RUNCLIENTSCRIPT(Js5ServerProtId.RUNCLIENTSCRIPT, Prot.VAR_SHORT),
    TRIGGER_ONDIALOGABORT(Js5ServerProtId.TRIGGER_ONDIALOGABORT, 0),
    MESSAGE_GAME(Js5ServerProtId.MESSAGE_GAME, Prot.VAR_BYTE),
    CHAT_FILTER_SETTINGS(Js5ServerProtId.CHAT_FILTER_SETTINGS, 2),
    CHAT_FILTER_SETTINGS_PRIVATECHAT(Js5ServerProtId.CHAT_FILTER_SETTINGS_PRIVATECHAT, 1),
    UPDATE_TRADINGPOST(Js5ServerProtId.UPDATE_TRADINGPOST, Prot.VAR_SHORT),
    UPDATE_STOCKMARKET_SLOT(Js5ServerProtId.UPDATE_STOCKMARKET_SLOT, 20),

    // Misc. client state packets
    HINT_ARROW(Js5ServerProtId.HINT_ARROW, 6),
    RESET_ANIMS(Js5ServerProtId.RESET_ANIMS, 0),
    UPDATE_REBOOT_TIMER(Js5ServerProtId.UPDATE_REBOOT_TIMER, 2),
    HEATMAP_TOGGLE(Js5ServerProtId.HEATMAP_TOGGLE, 1),
    MINIMAP_TOGGLE(Js5ServerProtId.MINIMAP_TOGGLE, 1),
    SERVER_TICK_END(Js5ServerProtId.SERVER_TICK_END, 0),

    // Misc. client packets
    URL_OPEN(Js5ServerProtId.URL_OPEN, Prot.VAR_SHORT),
    UPDATE_SITESETTINGS(Js5ServerProtId.UPDATE_SITESETTINGS, Prot.VAR_BYTE),
    UPDATE_UID192(Js5ServerProtId.UPDATE_UID192, 28),
    REFLECTION_CHECKER(Js5ServerProtId.REFLECTION_CHECKER, Prot.VAR_SHORT),
    SEND_PING(Js5ServerProtId.SEND_PING, 8),
    HISCORE_REPLY(Js5ServerProtId.HISCORE_REPLY, Prot.VAR_SHORT),
}
